service: test-star-wars-api
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  region: us-east-2
  timeout: 10
  environment:
    DB_NAME: ${env.DB_NAME, null}
    DB_USER: ${env.DB_USER, null}
    DB_PASS: ${env.DB_PASS, null}
    DB_HOST: ${env.DB_HOST, null}
package:
  individually: true
  exclude:
    - package-lock.json
    - .github/**
    - aws/**
    - .env_template
    - README.md

functions:
  app:
    handler: index.handler
    timeout: 20
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
