service: test-star-wars-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'test'}
  region: us-east-2
  timeout: 10
  environment:
    # DB_NAME: ${env.DB_NAME, null}
    # DB_USER: ${env.DB_USER, null}
    # DB_PASS: ${env.DB_PASS, null}
    # DB_HOST: ${env.DB_HOST, null}
    # PORT: ${env.PORT, null}
    DB_NAME: star_wars_db
    DB_USER: root
    DB_PASS: root
    DB_HOST: "127.0.0.1"
    PORT: 3000
package:
  individually: true
  exclude:
    - package-lock.json
    - .github/**
    - aws/**
    - .env_template
    - .env.*
    - README.md

functions:
  translator:
    handler: src/translator/index.handler
    timeout: 30
    events:
      - http:
          path: /translation/{proxy+}
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Timezone
  starshipApp:
    handler: src/starships-management/index.handler
    timeout: 30
    events:
      - http:
          path: /starships/{proxy+}
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - Authorization
              - X-Timezone
plugins:
  - serverless-offline
